export const EXAMPLES = [
  {
    id: "poster",
    name: "Đơn poster 2200×3000",
    title: "Trim trái/phải 25 mm, A/B/C cùng dài 1000 — 1 tấm, hiệu suất 97.73%, hao hụt 2.27%",
    highlight: true,
    allowRotation: false,
    allowPieceRotation: false,
    allowSheetRotation: false,
    sheet: { width: 2200, height: 3000 },
    trim: { left: 25, right: 25, top: 0, bottom: 0 },
    items: [
      { name: "A", width: 700, height: 1000, quantity: 3 },
      { name: "B", width: 800, height: 1000, quantity: 3 },
      { name: "C", width: 650, height: 1000, quantity: 3 },
    ],
  },
  {
    id: "gep-du",
    name: "Ghép dư hàng",
    title: "Trộn 60×50 với 40×50 lấp kín ngang: 1 tấm, 0 rác — tách khổ phải 2 tấm",
    highlight: true,
    allowRotation: true,
    sheet: { width: 100, height: 200 },
    items: [
      { name: "A", width: 60, height: 50, quantity: 3 },
      { name: "B", width: 40, height: 50, quantity: 3 },
      { name: "C", width: 50, height: 25, quantity: 4 },
    ],
  },
  {
    id: "it-to",
    name: "Ít tờ hơn",
    title: "Tách khổ còn 6 tờ, hao 1.9% — trộn hàng lại thành 7 tờ",
    highlight: true,
    allowRotation: true,
    sheet: { width: 80, height: 120 },
    items: [
      { name: "A", width: 50, height: 40, quantity: 12 },
      { name: "B", width: 30, height: 40, quantity: 10 },
      { name: "C", width: 40, height: 30, quantity: 8 },
      { name: "D", width: 20, height: 20, quantity: 16 },
      { name: "E", width: 25, height: 15, quantity: 12 },
    ],
  },
  {
    id: "gan-kin",
    name: "Gần lấp kín",
    title: "5 khổ nhét 1 tấm, rác trong hàng chỉ 200 — phương án kém phải 2 tấm",
    highlight: true,
    allowRotation: true,
    sheet: { width: 100, height: 200 },
    items: [
      { name: "A", width: 40, height: 30, quantity: 6 },
      { name: "B", width: 20, height: 30, quantity: 8 },
      { name: "C", width: 50, height: 20, quantity: 4 },
      { name: "D", width: 25, height: 20, quantity: 4 },
      { name: "E", width: 10, height: 10, quantity: 8 },
    ],
  },
  {
    id: "tron-kin",
    name: "Trộn không rác",
    title: "Hàng 40+20 và 60+30+15 lấp kín ngang, scrap = 0 trên 2 tấm",
    highlight: true,
    allowRotation: true,
    sheet: { width: 120, height: 240 },
    items: [
      { name: "A", width: 40, height: 30, quantity: 16 },
      { name: "B", width: 20, height: 30, quantity: 16 },
      { name: "C", width: 60, height: 20, quantity: 12 },
      { name: "D", width: 30, height: 20, quantity: 8 },
      { name: "E", width: 15, height: 20, quantity: 8 },
    ],
  },
  {
    id: "don-xuong",
    name: "Đơn xưởng",
    title: "7 khổ, 144 tấm: trộn hàng giảm rác so với tách khổ",
    highlight: true,
    allowRotation: true,
    sheet: { width: 100, height: 140 },
    items: [
      { name: "A", width: 45, height: 35, quantity: 18 },
      { name: "B", width: 35, height: 25, quantity: 20 },
      { name: "C", width: 30, height: 20, quantity: 28 },
      { name: "D", width: 50, height: 20, quantity: 10 },
      { name: "E", width: 15, height: 15, quantity: 36 },
      { name: "F", width: 25, height: 10, quantity: 24 },
      { name: "G", width: 40, height: 30, quantity: 8 },
    ],
  },
  {
    id: "xoay-ghep",
    name: "Xoay ghép hàng",
    title: "Xoay hướng cắt tấm nguyên rồi trộn hàng, rác ít hơn tách khổ",
    highlight: true,
    allowRotation: true,
    allowPieceRotation: true,
    allowSheetRotation: true,
    sheet: { width: 80, height: 160 },
    items: [
      { name: "A", width: 50, height: 30, quantity: 8 },
      { name: "B", width: 30, height: 20, quantity: 12 },
      { name: "C", width: 45, height: 20, quantity: 8 },
      { name: "D", width: 20, height: 40, quantity: 10 },
      { name: "E", width: 25, height: 15, quantity: 12 },
    ],
  },
  {
    id: "chuan",
    name: "Đơn chuẩn",
    title: "Nhiều khổ trên một tấm lớn, có phần dư",
    allowRotation: true,
    sheet: { width: 100, height: 200 },
    items: [
      { name: "A", width: 10, height: 20, quantity: 10 },
      { name: "B", width: 5, height: 10, quantity: 15 },
      { name: "C", width: 2, height: 3, quantity: 20 },
    ],
  },
  {
    id: "lap-kin",
    name: "Lấp kín",
    title: "4 tấm 5×5 lấp kín tờ 10×10, không rác",
    allowRotation: true,
    sheet: { width: 10, height: 10 },
    items: [{ name: "5×5", width: 5, height: 5, quantity: 4 }],
  },
  {
    id: "tron-dai",
    name: "Trộn cùng dài",
    title: "Hai khổ cùng chiều dài, xếp chung một hàng",
    allowRotation: true,
    sheet: { width: 100, height: 20 },
    items: [
      { name: "A", width: 20, height: 10, quantity: 3 },
      { name: "B", width: 5, height: 10, quantity: 8 },
    ],
  },
  {
    id: "tron-xoay",
    name: "Trộn nhờ xoay",
    title: "Xoay 90° để hai khổ thành cùng chiều dài hàng",
    allowRotation: true,
    sheet: { width: 100, height: 40 },
    items: [
      { name: "A", width: 20, height: 10, quantity: 4 },
      { name: "B", width: 10, height: 5, quantity: 8 },
    ],
  },
  {
    id: "tach-hang",
    name: "Mỗi hàng một khổ",
    title: "Khổ khác chiều dài nên không trộn hàng",
    allowRotation: false,
    sheet: { width: 60, height: 50 },
    items: [
      { name: "A", width: 20, height: 20, quantity: 4 },
      { name: "B", width: 15, height: 10, quantity: 6 },
    ],
  },
  {
    id: "phai-xoay",
    name: "Phải xoay",
    title: "Khổ rộng hơn tấm, chỉ xếp được khi xoay 90°",
    allowRotation: true,
    sheet: { width: 20, height: 40 },
    items: [{ name: "A", width: 30, height: 10, quantity: 2 }],
  },
  {
    id: "cam-xoay",
    name: "Cấm xoay",
    title: "Cùng đơn với «Trộn nhờ xoay» nhưng tắt xoay — không chung hàng",
    allowRotation: false,
    sheet: { width: 100, height: 40 },
    items: [
      { name: "A", width: 20, height: 10, quantity: 4 },
      { name: "B", width: 10, height: 5, quantity: 8 },
    ],
  },
  {
    id: "nhieu-tam",
    name: "Nhiều tấm",
    title: "Đơn lớn hơn một tờ nguyên, phải dùng nhiều tấm",
    allowRotation: true,
    sheet: { width: 20, height: 20 },
    items: [{ name: "10×10", width: 10, height: 10, quantity: 9 }],
  },
  {
    id: "qua-to",
    name: "Khổ quá to",
    title: "Tấm cắt lớn hơn tấm nguyên, kể cả khi xoay",
    allowRotation: true,
    sheet: { width: 10, height: 10 },
    items: [{ name: "big", width: 12, height: 8, quantity: 1 }],
  },
  {
    id: "dung-dai",
    name: "Đúng chiều dài",
    title: "Hàng dài bằng tấm — không cần cắt ngang",
    allowRotation: false,
    sheet: { width: 100, height: 20 },
    items: [{ name: "A", width: 25, height: 20, quantity: 4 }],
  },
  {
    id: "dung-rong",
    name: "Đúng chiều rộng",
    title: "Tấm cắt đúng khổ ngang — không cần cắt dọc",
    allowRotation: false,
    sheet: { width: 30, height: 60 },
    items: [{ name: "A", width: 30, height: 20, quantity: 3 }],
  },
  {
    id: "vuong",
    name: "Hình vuông",
    title: "Khổ vuông, xoay 90° không đổi layout",
    allowRotation: true,
    sheet: { width: 40, height: 40 },
    items: [{ name: "10×10", width: 10, height: 10, quantity: 12 }],
  },
  {
    id: "du-nhieu",
    name: "Cắt ít dư nhiều",
    title: "Vùng cắt nhỏ trên tấm lớn — dùng để xem phóng vùng cắt",
    allowRotation: true,
    sheet: { width: 100, height: 200 },
    items: [
      { name: "A", width: 10, height: 20, quantity: 3 },
      { name: "B", width: 15, height: 10, quantity: 2 },
    ],
  },
  {
    id: "so-le",
    name: "Kích thước lẻ",
    title: "Kích thước không nguyên — nhánh greedy, không DP",
    allowRotation: true,
    sheet: { width: 100, height: 50 },
    items: [
      { name: "A", width: 12.5, height: 7.5, quantity: 8 },
      { name: "B", width: 20, height: 15, quantity: 3 },
    ],
  },
]

export function exampleById(id) {
  return EXAMPLES.find((e) => e.id === id) || EXAMPLES[0]
}
